import pickle
from abc import ABC, abstractmethod
from typing import TypeAlias

from spectrumapp_loader.dumps import BinaryDump, Dump
from spectrumapp_loader.parsers import BinaryParser
from spectrumapp_loader.types import FilePath


class AbstractLoader(ABC):

    @abstractmethod
    def load(self, filepath: FilePath, verbose: bool = False) -> Dump:
        raise NotImplementedError


class BinaryLoader(AbstractLoader):
    """Loader for Atoms's binary dump files generated by [ExternalDumper.exe](https://github.com/Exinker/external-dumper)."""

    def load(self, filepath: FilePath, verbose: bool = False) -> BinaryDump:
        assert filepath.endswith('.pkl'), '`BinaryLoader` supports only .pkl files!'

        with open(filepath, 'rb') as file:
            data = pickle.load(file)

        return BinaryDump.factory(
            parser=BinaryParser,
        ).create(
            data=data,
            verbose=verbose,
        )


Loader: TypeAlias = BinaryLoader
